[versions]
shadow = "9.3.1"
spotless = "8.2.1"
hytale = "2026.02.18-f3b8fff95"
mixin = "0.17.0+mixin.0.8.7"
mixinextras = "0.5.3"
guava = "33.5.0-jre"

[libraries]
shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
hytale = { group = "com.hypixel.hytale", name = "Server", version.ref = "hytale" }
mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-fabric", version.ref = "mixinextras" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
